[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
anchor_movie_review_program = "JByNmHphtaAeGoeB1f6k8JnVKjXvo9efyWGh24sdhg2C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[test]
startup_wait = 100000


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


